
let  a =id_cat[]=cat23&id_cat[]=cat02
####
GET http://localhost:3001/car/ HTTP/1.1
####
GET http://localhost:3001/category HTTP/1.1
####

 POST http://localhost:3000/api/rental HTTP/1.1
 Content-Type: application/json

 { 
  "extraDriver": 1,
    "amount": 80,
"distance": 25,
"driverAge": 25,
"endDate": "2021-05-10",
"extraInsurance": true,
"id_car": "car002",
"id_user": 1,
"startDate": "2021-05-09"
}